version: '3.3'
services:
    nginx:
        container_name: nginx
        build: ./nginx
        image: docker-server/nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./mysite:/srv/docker-server
          - ./log:/var/log/nginx
        depends_on:
          - django
          - mysql

    django:
        container_name: django
        build: ./mysite
        image: docker-server/django
        restart: always
        command: bash -c "uwsgi --ini uwsgi.ini && python manage.py migrate"
        volumes:
          - ./mysite:/srv/docker-server
          - ./log:/var/log/uwsgi
        ports:
          - "8000:8000"

    mysql:
      container_name: mysql
      image: mysql:latest
      restart: always
      command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      env_file: 
        - ".env"
      environment: 
        MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${DB_DATABASE}"
        MYSQL_USER: "${DB_USER}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
      volumes: 
        - /mnt/disks/disk1/mysql-data:/var/lib/mysql
      ports:
        - "3307:3306"